### ISSUE TITLE
NameError: global name 'candidat' is not defined

### ISSUE THREAD

**Issue by a3mon** [jwiegley/svndumptool#8]
I get this error, processing a dump file created with `svnadmin dump -r 5001:5002`. I don't get this error processing a dumpfile created with `svnadmin dump -r 0:5000`

```
Traceback (most recent call last):
  File "/usr/bin/svndumptool.py", line 140, in <module>
    sys.exit( func( appname, args ) )
  File "/usr/lib/python2.7/site-packages/svndump/props.py", line 133, in svndump_eolfix_revprop_cmdline
    copy_dump_file( args[1], args[2],  EolRevisionPropertyTransformer( args[0] ) )
  File "/usr/lib/python2.7/site-packages/svndump/__init__.py", line 75, in copy_dump_file
    found = oldRevToNewRev.has_key(candidat)
NameError: global name 'candidat' is not defined
```

**Comment by jwiegley** [comment]
This is only a mirror of `svndumptool`.
